# Generated by Django 3.2.6 on 2021-11-23 03:24

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0027_alter_newsprise_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='futuremodels',
            name='descriptions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
